#!/usr/bin/env python3
"""Builds the gallery section of the site out of the mockup's own index.

Nothing here is hand-written twice: the groups, the order and the captions come from
`mockups/index.html` (the gallery the mockup already had), the screenshots and their
dimensions come from `mockups/screenshots/`, and the app renders come from
`mockups/screenshots/app/`. The result is written into the block delimited by the
`gallery:begin` / `gallery:end` comments in `site/index.html`.

    python3 site/tools/build_gallery.py           # regenerate the block
    python3 site/tools/build_gallery.py --check    # fail if the block is stale (CI)

The generated markup is committed, so the grid exists with JavaScript disabled; the script
only adds the filtering and the lightbox on top of it. A screen added to
`mockups/index.html` therefore appears here after one run, and `--check` is what keeps the
committed block honest.
"""

from __future__ import annotations

import argparse
import html
import re
import struct
import sys
from dataclasses import dataclass, field
from pathlib import Path

BEGIN = "<!-- gallery:begin — generated by site/tools/build_gallery.py, do not edit by hand -->"
END = "<!-- gallery:end -->"

# The app renders have no mockup index to read, so their captions and form factors live here —
# keyed by file name. Adding a render means adding one line to this map (the only hand-kept
# list in this script): the client's own shots are not 2× the way the mockup's are, so their
# form factor cannot be read from the pixel size.
APP_RENDERS = {
    "01-sessions-list": ("Sessions — the list and its states", "mobile"),
    "02-chat": ("Chat — a streaming turn", "mobile"),
    "03-files": ("Files — browsing a workspace", "mobile"),
    "04-git-panel": ("Git — status, diff and log", "desktop"),
    "05-settings": ("Settings — the server's policy", "desktop"),
}


def png_size(path: Path) -> tuple[int, int]:
    """Reads a PNG's pixel dimensions from its IHDR chunk."""
    header = path.read_bytes()[:33]
    if header[12:16] != b"IHDR":
        raise ValueError(f"{path} is not a PNG")
    return struct.unpack(">II", header[16:24])


@dataclass
class Screen:
    slug: str
    title: str
    group: str
    group_slug: str
    num: str
    device: str
    source: str
    dark: str | None = None
    light: str | None = None
    thumb: str | None = None
    thumb_size: tuple[int, int] | None = None
    live: str | None = None


@dataclass
class Group:
    title: str
    slug: str
    screens: list[Screen] = field(default_factory=list)


def slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def device_of(thumb_body: str) -> str | None:
    """The form factor the mockup gallery declares for a thumb, if it declares one.

    `mockups/index.html` sizes each frame explicitly — `width:390px` for a phone, `1100px`
    for a desktop panel — and the breakpoints the app uses are the same ones (< 600 mobile,
    > 1024 desktop). A thumb without a declared width (the states board) is left to the image.
    """
    width = re.search(r'style="width:(\d+)px', thumb_body)
    if width is None:
        return None
    return "mobile" if int(width.group(1)) <= 600 else "desktop"


def parse_mockup_index(path: Path) -> list[Group]:
    """Reads the mockup gallery: its sections are the groups, its thumbs the screens."""
    markup = path.read_text(encoding="utf-8")
    groups: list[Group] = []
    seen: dict[str, Screen] = {}

    for chunk in re.split(r'<section class="group">', markup)[1:]:
        heading = re.search(r"<h2>(.*?)</h2>", chunk, re.S)
        title = html.unescape(re.sub(r"<span.*?</span>", "", heading.group(1), flags=re.S)).strip()
        group = Group(title=title, slug=slugify(title))
        for thumb in re.finditer(r'<a class="thumb" href="screens/([\w.-]+?)\.html">(.*?)</a>', chunk, re.S):
            slug, body = thumb.group(1), thumb.group(2)
            caption = re.search(r'<div class="caption"><span class="num">(.*?)</span>(.*?)</div>', body, re.S)
            if caption is None:
                continue
            num = html.unescape(re.sub(r"<.*?>", "", caption.group(1))).strip()
            label = html.unescape(re.sub(r"<.*?>", "", caption.group(2))).strip()
            if slug in seen:  # a screen listed twice keeps its first home
                continue
            screen = Screen(slug=slug, title=label, group=title, group_slug=group.slug,
                            num=num, device=device_of(body), source="mockup")
            seen[slug] = screen
            group.screens.append(screen)
        if group.screens:
            groups.append(group)
    return groups


def attach_mockup_renders(groups: list[Group], screenshots: Path, warnings: list[str]) -> None:
    """Points every screen at its renders and derives the form factor from the image."""
    for group in groups:
        for screen in group.screens:
            dark = screenshots / "dark" / f"{screen.slug}.png"
            light = screenshots / "light" / f"{screen.slug}.png"
            thumb = screenshots / "thumbs" / "dark" / f"{screen.slug}.png"
            if not dark.is_file():
                warnings.append(f"{screen.slug}: no render in screenshots/dark — run mockups/tools/shoot_screenshots.mjs")
                continue
            screen.dark = f"mockups/screenshots/dark/{screen.slug}.png"
            screen.live = f"mockups/screens/{screen.slug}.html"
            if light.is_file():
                screen.light = f"mockups/screenshots/light/{screen.slug}.png"
            width, height = png_size(dark)
            # A phone render is ~780 px wide over ~1520 px tall at 2×; a desktop panel is
            # wider than it is tall. Only thumbs that declare nothing (the states board) get
            # here — every other screen carried its form factor from the mockup index.
            if screen.device is None:
                screen.device = "desktop" if width / height > 1.2 else "mobile"
            if thumb.is_file():
                screen.thumb = f"mockups/screenshots/thumbs/dark/{screen.slug}.png"
                screen.thumb_size = png_size(thumb)
            else:
                screen.thumb = screen.dark


def app_group(screenshots: Path, warnings: list[str]) -> Group | None:
    """The Flutter client's own renders, as a group of their own."""
    directory = screenshots / "app"
    files = sorted(directory.glob("*.png")) if directory.is_dir() else []
    if not files:
        warnings.append("screenshots/app: no render of the Flutter client")
        return None
    group = Group(title="The Flutter client", slug="the-flutter-client")
    for index, file in enumerate(files, start=1):
        slug = file.stem
        entry = APP_RENDERS.get(slug)
        if entry is None:
            warnings.append(f"screenshots/app/{file.name}: no entry in APP_RENDERS — using the file name and the picture's shape")
            entry = (slug.replace("-", " "), None)
        caption, device = entry
        if device is None:
            width, height = png_size(file)
            device = "desktop" if width / height > 1.2 else "mobile"
        group.screens.append(Screen(
            slug=slug, title=caption, group=group.title, group_slug=group.slug,
            num=f"{index}", device=device, source="app",
            dark=f"mockups/screenshots/app/{file.name}", thumb=f"mockups/screenshots/app/{file.name}",
            thumb_size=png_size(file),
        ))
    return group


def esc(value: str) -> str:
    return html.escape(value, quote=True)


def render_filters(groups: list[Group], screens: list[Screen]) -> str:
    """The filter bar: the counts are computed here so they can never drift."""
    chips: list[str] = []
    chips.append(
        '<button class="chip" type="button" data-filter="group" data-value="all" aria-pressed="true">'
        f'All <span class="count">{len(screens)}</span></button>'
    )
    for group in groups:
        chips.append(
            f'<button class="chip" type="button" data-filter="group" data-value="{esc(group.slug)}" aria-pressed="false">'
            f'{esc(group.title)} <span class="count">{len(group.screens)}</span></button>'
        )
    devices = [("mobile", "Phone"), ("desktop", "Desktop")]
    device_chips = "".join(
        f'<button class="chip" type="button" data-filter="device" data-value="{value}" aria-pressed="false">'
        f'{label} <span class="count">{sum(1 for s in screens if s.device == value)}</span></button>'
        for value, label in devices
        if any(s.device == value for s in screens)
    )
    source_chips = "".join(
        f'<button class="chip" type="button" data-filter="source" data-value="{value}" aria-pressed="false">'
        f'{label} <span class="count">{sum(1 for s in screens if s.source == value)}</span></button>'
        for value, label in (("mockup", "Mockup"), ("app", "Flutter client"))
        if any(s.source == value for s in screens)
    )
    return """      <div class="filters" id="gallery-filters">
        <div class="row">
          <label class="row-label" for="gallery-search">Find a screen</label>
          <input class="search" id="gallery-search" type="search" placeholder="Type a name: chat, git, pairing…" autocomplete="off">
        </div>
        <div class="row"><span class="row-label">Area</span>
          {chips}
        </div>
        <div class="row"><span class="row-label">Form</span>
          {devices}
        </div>
        <div class="row"><span class="row-label">Source</span>
          {sources}
        </div>
      </div>
      <p class="gallery-count" id="gallery-count">{total} screens: {mockups} from the mockup, {apps} rendered from the Flutter client.</p>
""".format(chips="\n          ".join(chips), devices=device_chips, sources=source_chips,
           total=len(screens), mockups=sum(1 for s in screens if s.source == "mockup"),
           apps=sum(1 for s in screens if s.source == "app"))


def render_tile(screen: Screen) -> str:
    size = f' width="{screen.thumb_size[0]}" height="{screen.thumb_size[1]}"' if screen.thumb_size else ""
    origin = "mockup" if screen.source == "mockup" else "the Flutter client"
    alt = f"{screen.title} — {origin}"
    thumb_light = screen.thumb.replace("/thumbs/dark/", "/thumbs/light/") if screen.thumb else ""
    attributes = [
        f'class="tile"',
        f'data-slug="{esc(screen.slug)}"',
        f'data-title="{esc(screen.title)}"' if screen.title else 'data-title=""',
        f'data-group="{esc(screen.group_slug)}"',
        f'data-device="{screen.device}"',
        f'data-source="{screen.source}"',
        f'data-dark="{esc(screen.dark or "")}"',
        f'data-light="{esc(screen.light or screen.dark or "")}"',
        f'data-thumb-dark="{esc(screen.thumb or "")}"',
        f'data-thumb-light="{esc(thumb_light)}"',
        f'data-live="{esc(screen.live or "")}"',
    ]
    num = f'<span class="num">{esc(screen.num)}</span>' if screen.num else ""
    return (
        f'      <figure {" ".join(attributes)}>\n'
        f'        <button class="open" type="button" aria-label="Enlarge {esc(screen.title)}">\n'
        f'          <img src="{esc(screen.thumb or "")}" alt="{esc(alt)}" loading="lazy"{size}>\n'
        f'        </button>\n'
        f'        <figcaption>{esc(screen.title)}</figcaption>\n'
        f'        <p class="meta">{num}<span>{esc(screen.group)}</span></p>\n'
        f'      </figure>'
    )


def render_block(groups: list[Group], screens: list[Screen]) -> str:
    tiles: list[str] = []
    for group in groups:
        tiles.extend(render_tile(screen) for screen in group.screens)
    return (
        f"{BEGIN}\n"
        + render_filters(groups, screens)
        + '      <div class="gallery-grid" id="gallery-grid">\n'
        + "\n".join(tiles)
        + "\n      </div>\n"
        + '      <p class="gallery-empty" id="gallery-empty" hidden>No screen matches that filter. '
          '<button class="chip" type="button" id="gallery-reset">Clear the filters</button></p>\n'
        + f"{END}"
    )


def build(root: Path) -> tuple[str, list[str]]:
    mockups = root / "mockups"
    warnings: list[str] = []
    groups = parse_mockup_index(mockups / "index.html")
    attach_mockup_renders(groups, mockups / "screenshots", warnings)
    for group in groups:
        group.screens = [screen for screen in group.screens if screen.dark]
    groups = [group for group in groups if group.screens]
    app = app_group(mockups / "screenshots", warnings)
    if app is not None:
        groups.append(app)
    screens = [screen for group in groups for screen in group.screens]
    return render_block(groups, screens), warnings


def replace_block(page: Path, block: str) -> str:
    markup = page.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(markup):
        raise SystemExit(f"build_gallery: the {BEGIN!r} block is missing from {page}")
    return pattern.sub(lambda _: block, markup)


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description="Regenerate the gallery block of the site.")
    parser.add_argument("--root", default=str(root), help=argparse.SUPPRESS)
    parser.add_argument("--check", action="store_true", help="fail instead of writing when the block is stale")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    page = root / "site" / "index.html"
    block, warnings = build(root)
    for warning in warnings:
        print(f"build_gallery: warning: {warning}", file=sys.stderr)
    wanted = replace_block(page, block)
    current = page.read_text(encoding="utf-8")
    tiles = block.count('<figure class="tile"')
    if wanted == current:
        print(f"gallery is up to date ({tiles} screens)")
        return 0
    if args.check:
        print(f"gallery is stale: {tiles} screens expected — run site/tools/build_gallery.py", file=sys.stderr)
        return 1
    page.write_text(wanted, encoding="utf-8")
    print(f"gallery written: {tiles} screens")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
