// Command genschemas writes the Go file that embeds one JSON schema as a string
// literal and registers it with internal/protocol/gen from an init(). It is the
// second step of scripts/gen.sh, which calls it once per schemas/<name>.json:
//
//	go run ./scripts/genschemas -schema ../schemas/ws.json -name ws \
//	    -out internal/protocol/gen/ws_schema_gen.go
//
// Output is deterministic and gofmt'd, so regenerating an unchanged schema
// rewrites the same bytes and leaves the tree clean.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
)

func main() {
	schema := flag.String("schema", "", "path of the JSON schema to embed")
	name := flag.String("name", "", "schema name used by gen.SchemaJSON")
	out := flag.String("out", "", "path of the Go file to write")
	flag.Parse()

	if err := run(*schema, *name, *out); err != nil {
		fmt.Fprintf(os.Stderr, "genschemas: %v\n", err)
		os.Exit(1)
	}
}

func run(schema, name, out string) error {
	switch {
	case schema == "":
		return fmt.Errorf("-schema is required")
	case name == "":
		return fmt.Errorf("-name is required")
	case out == "":
		return fmt.Errorf("-out is required")
	}

	data, err := os.ReadFile(schema)
	if err != nil {
		return err
	}
	if !json.Valid(data) {
		return fmt.Errorf("%s: not valid JSON", schema)
	}

	src := fmt.Sprintf(`// Code generated by scripts/gen.sh from %s. DO NOT EDIT.

package gen

func init() {
	registerSchema(%q, []byte(%s))
}
`, filepath.ToSlash(schema), name, strconv.Quote(string(data)))

	formatted, err := format.Source([]byte(src))
	if err != nil {
		return fmt.Errorf("format generated source for %s: %w", name, err)
	}
	if existing, err := os.ReadFile(out); err == nil && bytes.Equal(existing, formatted) {
		return nil
	}
	return os.WriteFile(out, formatted, 0o644)
}
